# Generated by Django 5.1.1 on 2024-09-12 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("stations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets_as_destination",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="reservations.passenger",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets_as_source",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trains_as_destination",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trains_as_source",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="reservations.train",
            ),
        ),
    ]
